INSERT INTO `COUNTRY` (`NAME`) VALUES ('INDIA');
INSERT INTO `COUNTRY` (`NAME`) VALUES ('AUSTRIA');
INSERT INTO `COUNTRY` (`NAME`) VALUES ('NEW ZEALAND');
INSERT INTO `COUNTRY` (`NAME`) VALUES ('IRELAND');
INSERT INTO `COUNTRY` (`NAME`) VALUES ('RUSSIA');