management.endpoints.web.exposure.include: "*"
management:
  security:
    enabled: false
debug: true
server:
  port: 9099
  servlet:
    context-path: /fresh

#hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
#
spring:
  jpa:
  hibernate.ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3307/testdb
    username: vijay
    password: vijay123